version: '3'
services:
  server:
    # image: nghiack7/go-server:lastest
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/app.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
  app:
    # image: nghiack7/cryptop-app:latest
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    ports:
      - "3000:3000"